# Generated by Django 5.1 on 2024-08-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nutrient_images/'),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='nitrogen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='phosphorus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
