# Generated by Django 5.1 on 2024-08-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0003_alter_nutrient_amount_alter_nutrient_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrient',
            name='image',
        ),
    ]
