# Generated by Django 5.1 on 2024-08-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0004_remove_nutrient_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrient',
            name='unit',
        ),
    ]
