# Generated by Django 5.1 on 2024-08-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='image',
        ),
        migrations.AddField(
            model_name='plant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='plant_photos/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
